CustomSystemUIModule: Fix compile
frameworks/base/packages/SystemUI/src/com/android/systemui/custom/dagger/CustomSystemUIModule.java:111: error: constructor BatteryControllerImpl in class BatteryControllerImpl cannot be applied to given types;
        BatteryController bC = new BatteryControllerImpl(
                               ^
  required: Context,EnhancedEstimates,PowerManager,BroadcastDispatcher,DemoModeController,Handler,Handler,UserContentResolverProvider
  found: Context,EnhancedEstimates,PowerManager,BroadcastDispatcher,DemoModeController,Handler,Handler
  reason: actual and formal argument lists differ in length
1 error
17:07:17 Got signal: interrupt
17:07:17 ninja failed with: exit status 130

Change-Id: Ia74a557653a145b6e37d8b2b0745f2bd7c6dec9e